export const routes = {
  home: '/',
  fazer: '/fazer',
  fazerHoje: '/fazer/hoje',
  fazerTimeline: '/fazer/timeline',
  fazerRitual: '/fazer/ritual',
  fazerEncerramento: '/fazer/encerramento',
  fazerAtencao: '/fazer/atencao',
  planejar: '/planejar',
  planejarMetas: '/planejar/metas',
  planejarProjetos: '/planejar/projetos',
  planejarHabitos: '/planejar/habitos',
  planejarInegociaveis: '/planejar/inegociaveis',
  planejarRevisaoSemanal: '/planejar/revisao-semanal',
  memoria: '/memoria',
  memoriaInbox: '/memoria/inbox',
  memoriaItens: '/memoria/itens',
  memoriaCaixola: '/memoria/caixola',
  memoriaAtalhos: '/memoria/atalhos',
  memoriaTemplates: '/memoria/templates',
  memoriaArquivados: '/memoria/arquivados',
  memoriaAnexos: '/memoria/anexos',
  central: '/central',
  login: '/login',
  signup: '/signup',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',
} as const;

export const tabRoutes = [
  { label: 'Fazer', path: routes.fazer },
  { label: 'Planejar', path: routes.planejar },
  { label: 'Memória', path: routes.memoria },
] as const;
